version: '3.1'

services:

  mongo-rs:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-rs-data:/data/db
      - ./data:/var/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    deploy: 
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 100M
  
volumes: 
    mongo-rs-data:
